### PR TITLE
Add openid grant to server and fix .travis.yml

### LINKED ISSUE #74: Improve OpenID Documentation
Please add to the openID documentation, that you musst add a new grant type

$config['use_openid_connect'] = true;
$config['issuer'] = 'brentertainment.com';
$server = new OAuth2\Server($config);
$server->addGrantType(new OAuth2\OpenID\GrantType\AuthorizationCode($storage));

### PR DESCRIPTION
**Pull request by c-reber**
Updated documentation for OpenID Connect to add grant type.

Fixes #74. This will help a lot of people struggling with this missing line of code.

Also added Ruby version to Travis CI config to get builds working again.

### CODE REVIEW

**Comment by bshaffer** [comment]
This step isn't necessary, though. As long as `use_openid_connect` is set to true and your server has a storage class implementing `AuthorizationCode` (which should be any of them), then the `OAuth2\OpenID\GrantType\AuthorizationCode` will be added automatically (see [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Server.php#L749)).

**Comment by bshaffer** [comment]
I've added your travis fix: 61f6df4feab8f85c5a872e4ae153f3eef9b2b611 Thank you!

**Comment by c-reber** [comment]
Thank you for pointing me the right direction!

My issue was that I added grant types manually to the server object. In that case the  method [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Server.php#L726) is never called.

Is it best practice to rely on that method or should the grant types added manually using the addGrantType-method?

I wonder if there should be a note that the grant types must not be added to work in the example provided in documentation.

**Comment by bshaffer** [comment]
@c-reber If you use the `addGrantTypes` method, but add the proper `OpenID` classes, then it'll work. But yes, it's a little confusing. The Server class essentially tries to set everything up intelligently and if you do things manually such as `addGrantTypes` then this behavior no longer takes place.

I agree it can get confusing. One way to improve this would be to change it (in the next major version) so everything is set up *initially* (instead of lazy-loading later). Another way would be to document the behavior, as you have mentioned. I would definitely be open to a solid improvement in the documentation such as the note you mention.

**Comment by bshaffer** [comment]
Closing this for now, since there's nothing left to merge in this PR.

**Pull request closed without merging**
